name: buermans_laa_bench
channels:
    - conda-forge
    - bioconda
dependencies:
    - pblaa=2.4.2
    - pbbam=1.6.0
    - pbccs=6.0.0
    - pbmm2=1.4.0
    - pbsv=2.6.0
    - lima=2.2.0
    - bcftools=1.10.2
    - samtools=1.10
    - pysam=0.16.0.1